name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Decode and Save SSH Key
        run: |
          echo "$EC2_KEY" | base64 --decode > /tmp/test-cicd.pem
          chmod 600 /tmp/test-cicd.pem

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i /tmp/test-cicd.pem $EC2_USER@$EC2_HOST << 'EOF'
          cd /var/www/laravel
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          exit
          EOF
        env:
          EC2_USER: ubuntu # Replace with your EC2 username
          EC2_HOST: 44.223.17.83 # Replace with your EC2 public IP
