name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 44.223.17.83 # Set your EC2 hostname or IP address
      EC2_USER: ubuntu
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Variables
        run: |
          echo "EC2_HOST is: $EC2_HOST"

      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          if [ -n "$EC2_HOST" ]; then
            ssh-keyscan -H "$EC2_HOST" >> ~/.ssh/known_hosts
          else
            echo "Error: EC2_HOST is not set."
            exit 1
          fi
