name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Decode and save SSH private key from GitHub Secrets
      - name: Decode and Save SSH Key
        run: |
          echo "$EC2_KEY" | base64 --decode > /tmp/test-cicd.pem
          chmod 600 /tmp/test-cicd.pem

      # Step 3: Add EC2 Host to Known Hosts to avoid SSH warnings
      - name: Debug EC2_HOST and Add to Known Hosts
        run: |
          echo "EC2_HOST is: $EC2_HOST"
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      # Step 4: SSH to EC2 and run deployment commands
      - name: SSH to EC2 and Deploy
        run: |
          echo "EC2_USER is: $EC2_USER"
          echo "EC2_HOST is: $EC2_HOST"
          ssh -v -i /tmp/test-cicd.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST << 'EOF'
            # Navigate to your Laravel project directory
            cd /var/www/laravel

            # Pull the latest code from GitHub
            git pull origin main

            # Install Composer dependencies (production only)
            composer install --no-dev --optimize-autoloader

            # Run database migrations
            php artisan migrate --force

            # Clear and cache config
            php artisan config:cache

            # Clear and cache routes
            php artisan route:cache

            # Exit SSH session
            exit
          EOF
