name: Deploy to EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      EC2_HOST: 44.223.17.83 # Replace with your EC2 instance IP
      EC2_USER: ubuntu # EC2 user for Ubuntu instances
      EC2_KEY: ${{ secrets.EC2_KEY }} # GitHub Secret for your private key

    steps:
      # Step 1: Checkout code from GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Decode and save SSH private key from GitHub Secrets
      - name: Decode and Save SSH Key
        run: |
          echo "$EC2_KEY" > /tmp/test-cicd.pem
          chmod 600 /tmp/test-cicd.pem

      # Step 3: Add EC2 Host to Known Hosts to avoid SSH warnings
      - name: Add EC2 Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts

      # Step 4: SSH to EC2 and run deployment commands
      - name: SSH to EC2 and Deploy
        run: |
          ssh -v -i /tmp/test-cicd.pem -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $EC2_USER@$EC2_HOST << 'EOF'
            # Fix permissions for the project files
            sudo chown -R www-data:www-data /var/www/laravel
            sudo chmod -R 755 /var/www/laravel

            # Navigate to your Laravel project directory
            cd /var/www/laravel

            # Pull the latest code from GitHub
            sudo git pull origin main --no-ff

            # Install Composer dependencies (production only)
            sudo composer install --no-dev --optimize-autoloader --no-plugins

            # Run database migrations if needed
            # Uncomment the next line to run migrations
            #sudo php artisan migrate --force

            # Clear and cache config
            sudo php artisan config:cache

            # Clear and cache routes
            sudo php artisan route:cache

            # Clear and cache views
            sudo php artisan view:cache

            # Restart the Nginx service to reflect the changes
            sudo systemctl restart nginx

            # Exit SSH session
            exit
          EOF
